// Chinese telephone area codes (固话区号) for major cities and prefectures.
// Codes are 3-4 digits; leading 0 is part of the long-distance prefix.

export interface AreaCodeEntry {
  code: string;
  city: string;
  province: string;
}

export const AREA_CODES: AreaCodeEntry[] = [
  { code: "010", city: "北京市", province: "北京市" },
  { code: "021", city: "上海市", province: "上海市" },
  { code: "022", city: "天津市", province: "天津市" },
  { code: "023", city: "重庆市", province: "重庆市" },

  // 河北
  { code: "0311", city: "石家庄市", province: "河北省" },
  { code: "0312", city: "保定市", province: "河北省" },
  { code: "0313", city: "张家口市", province: "河北省" },
  { code: "0314", city: "承德市", province: "河北省" },
  { code: "0315", city: "唐山市", province: "河北省" },
  { code: "0316", city: "廊坊市", province: "河北省" },
  { code: "0317", city: "沧州市", province: "河北省" },
  { code: "0318", city: "衡水市", province: "河北省" },
  { code: "0319", city: "邢台市", province: "河北省" },
  { code: "0335", city: "秦皇岛市", province: "河北省" },
  { code: "0310", city: "邯郸市", province: "河北省" },

  // 山西
  { code: "0351", city: "太原市", province: "山西省" },
  { code: "0352", city: "大同市", province: "山西省" },
  { code: "0353", city: "阳泉市", province: "山西省" },
  { code: "0354", city: "晋中市", province: "山西省" },
  { code: "0355", city: "长治市", province: "山西省" },
  { code: "0356", city: "晋城市", province: "山西省" },
  { code: "0357", city: "临汾市", province: "山西省" },
  { code: "0358", city: "吕梁市", province: "山西省" },
  { code: "0359", city: "运城市", province: "山西省" },
  { code: "0349", city: "朔州市", province: "山西省" },
  { code: "0350", city: "忻州市", province: "山西省" },

  // 辽宁
  { code: "024", city: "沈阳市", province: "辽宁省" },
  { code: "0411", city: "大连市", province: "辽宁省" },
  { code: "0412", city: "鞍山市", province: "辽宁省" },
  { code: "0413", city: "抚顺市", province: "辽宁省" },
  { code: "0414", city: "本溪市", province: "辽宁省" },
  { code: "0415", city: "丹东市", province: "辽宁省" },
  { code: "0416", city: "锦州市", province: "辽宁省" },
  { code: "0417", city: "营口市", province: "辽宁省" },
  { code: "0418", city: "阜新市", province: "辽宁省" },
  { code: "0419", city: "辽阳市", province: "辽宁省" },
  { code: "0421", city: "朝阳市", province: "辽宁省" },
  { code: "0427", city: "盘锦市", province: "辽宁省" },
  { code: "0429", city: "葫芦岛市", province: "辽宁省" },
  { code: "0410", city: "铁岭市", province: "辽宁省" },

  // 吉林
  { code: "0431", city: "长春市", province: "吉林省" },
  { code: "0432", city: "吉林市", province: "吉林省" },
  { code: "0433", city: "延边朝鲜族自治州", province: "吉林省" },
  { code: "0434", city: "四平市", province: "吉林省" },
  { code: "0435", city: "辽源市", province: "吉林省" },
  { code: "0436", city: "白城市", province: "吉林省" },
  { code: "0437", city: "松原市", province: "吉林省" },
  { code: "0438", city: "白山市", province: "吉林省" },
  { code: "0439", city: "通化市", province: "吉林省" },

  // 黑龙江
  { code: "0451", city: "哈尔滨市", province: "黑龙江省" },
  { code: "0452", city: "齐齐哈尔市", province: "黑龙江省" },
  { code: "0453", city: "牡丹江市", province: "黑龙江省" },
  { code: "0454", city: "佳木斯市", province: "黑龙江省" },
  { code: "0455", city: "绥化市", province: "黑龙江省" },
  { code: "0456", city: "黑河市", province: "黑龙江省" },
  { code: "0457", city: "大兴安岭地区", province: "黑龙江省" },
  { code: "0458", city: "伊春市", province: "黑龙江省" },
  { code: "0459", city: "大庆市", province: "黑龙江省" },
  { code: "0464", city: "七台河市", province: "黑龙江省" },
  { code: "0467", city: "鸡西市", province: "黑龙江省" },
  { code: "0468", city: "鹤岗市", province: "黑龙江省" },
  { code: "0469", city: "双鸭山市", province: "黑龙江省" },

  // 江苏
  { code: "025", city: "南京市", province: "江苏省" },
  { code: "0510", city: "无锡市", province: "江苏省" },
  { code: "0511", city: "镇江市", province: "江苏省" },
  { code: "0512", city: "苏州市", province: "江苏省" },
  { code: "0513", city: "南通市", province: "江苏省" },
  { code: "0514", city: "扬州市", province: "江苏省" },
  { code: "0515", city: "盐城市", province: "江苏省" },
  { code: "0516", city: "徐州市", province: "江苏省" },
  { code: "0517", city: "淮安市", province: "江苏省" },
  { code: "0518", city: "连云港市", province: "江苏省" },
  { code: "0519", city: "常州市", province: "江苏省" },
  { code: "0523", city: "泰州市", province: "江苏省" },
  { code: "0527", city: "宿迁市", province: "江苏省" },

  // 浙江
  { code: "0571", city: "杭州市", province: "浙江省" },
  { code: "0572", city: "湖州市", province: "浙江省" },
  { code: "0573", city: "嘉兴市", province: "浙江省" },
  { code: "0574", city: "宁波市", province: "浙江省" },
  { code: "0575", city: "绍兴市", province: "浙江省" },
  { code: "0576", city: "台州市", province: "浙江省" },
  { code: "0577", city: "温州市", province: "浙江省" },
  { code: "0578", city: "丽水市", province: "浙江省" },
  { code: "0579", city: "金华市", province: "浙江省" },
  { code: "0580", city: "舟山市", province: "浙江省" },
  { code: "0570", city: "衢州市", province: "浙江省" },

  // 安徽
  { code: "0551", city: "合肥市", province: "安徽省" },
  { code: "0552", city: "蚌埠市", province: "安徽省" },
  { code: "0553", city: "芜湖市", province: "安徽省" },
  { code: "0554", city: "淮南市", province: "安徽省" },
  { code: "0555", city: "马鞍山市", province: "安徽省" },
  { code: "0556", city: "安庆市", province: "安徽省" },
  { code: "0557", city: "宿州市", province: "安徽省" },
  { code: "0558", city: "阜阳市", province: "安徽省" },
  { code: "0559", city: "黄山市", province: "安徽省" },
  { code: "0561", city: "淮北市", province: "安徽省" },
  { code: "0562", city: "铜陵市", province: "安徽省" },
  { code: "0563", city: "宣城市", province: "安徽省" },
  { code: "0564", city: "六安市", province: "安徽省" },
  { code: "0565", city: "巢湖市", province: "安徽省" },
  { code: "0566", city: "池州市", province: "安徽省" },
  { code: "0570", city: "滁州市", province: "安徽省" },

  // 福建
  { code: "0591", city: "福州市", province: "福建省" },
  { code: "0592", city: "厦门市", province: "福建省" },
  { code: "0593", city: "宁德市", province: "福建省" },
  { code: "0594", city: "莆田市", province: "福建省" },
  { code: "0595", city: "泉州市", province: "福建省" },
  { code: "0596", city: "漳州市", province: "福建省" },
  { code: "0597", city: "龙岩市", province: "福建省" },
  { code: "0598", city: "三明市", province: "福建省" },
  { code: "0599", city: "南平市", province: "福建省" },

  // 江西
  { code: "0791", city: "南昌市", province: "江西省" },
  { code: "0792", city: "九江市", province: "江西省" },
  { code: "0793", city: "上饶市", province: "江西省" },
  { code: "0794", city: "抚州市", province: "江西省" },
  { code: "0795", city: "宜春市", province: "江西省" },
  { code: "0796", city: "吉安市", province: "江西省" },
  { code: "0797", city: "赣州市", province: "江西省" },
  { code: "0798", city: "景德镇市", province: "江西省" },
  { code: "0799", city: "萍乡市", province: "江西省" },
  { code: "0701", city: "鹰潭市", province: "江西省" },
  { code: "0790", city: "新余市", province: "江西省" },

  // 山东
  { code: "0531", city: "济南市", province: "山东省" },
  { code: "0532", city: "青岛市", province: "山东省" },
  { code: "0533", city: "淄博市", province: "山东省" },
  { code: "0534", city: "德州市", province: "山东省" },
  { code: "0535", city: "烟台市", province: "山东省" },
  { code: "0536", city: "潍坊市", province: "山东省" },
  { code: "0537", city: "济宁市", province: "山东省" },
  { code: "0538", city: "泰安市", province: "山东省" },
  { code: "0539", city: "临沂市", province: "山东省" },
  { code: "0543", city: "滨州市", province: "山东省" },
  { code: "0546", city: "东营市", province: "山东省" },
  { code: "0631", city: "威海市", province: "山东省" },
  { code: "0632", city: "枣庄市", province: "山东省" },
  { code: "0633", city: "日照市", province: "山东省" },
  { code: "0634", city: "莱芜市", province: "山东省" },
  { code: "0635", city: "聊城市", province: "山东省" },
  { code: "0530", city: "菏泽市", province: "山东省" },

  // 河南
  { code: "0371", city: "郑州市", province: "河南省" },
  { code: "0372", city: "安阳市", province: "河南省" },
  { code: "0373", city: "新乡市", province: "河南省" },
  { code: "0374", city: "许昌市", province: "河南省" },
  { code: "0375", city: "平顶山市", province: "河南省" },
  { code: "0376", city: "信阳市", province: "河南省" },
  { code: "0377", city: "南阳市", province: "河南省" },
  { code: "0378", city: "开封市", province: "河南省" },
  { code: "0379", city: "洛阳市", province: "河南省" },
  { code: "0391", city: "焦作市", province: "河南省" },
  { code: "0392", city: "鹤壁市", province: "河南省" },
  { code: "0393", city: "濮阳市", province: "河南省" },
  { code: "0394", city: "周口市", province: "河南省" },
  { code: "0395", city: "漯河市", province: "河南省" },
  { code: "0396", city: "驻马店市", province: "河南省" },
  { code: "0398", city: "三门峡市", province: "河南省" },
  { code: "0370", city: "商丘市", province: "河南省" },

  // 湖北
  { code: "027", city: "武汉市", province: "湖北省" },
  { code: "0710", city: "襄阳市", province: "湖北省" },
  { code: "0711", city: "鄂州市", province: "湖北省" },
  { code: "0712", city: "孝感市", province: "湖北省" },
  { code: "0713", city: "黄冈市", province: "湖北省" },
  { code: "0714", city: "黄石市", province: "湖北省" },
  { code: "0715", city: "咸宁市", province: "湖北省" },
  { code: "0716", city: "荆州市", province: "湖北省" },
  { code: "0717", city: "宜昌市", province: "湖北省" },
  { code: "0718", city: "恩施土家族苗族自治州", province: "湖北省" },
  { code: "0719", city: "十堰市", province: "湖北省" },
  { code: "0722", city: "随州市", province: "湖北省" },
  { code: "0724", city: "荆门市", province: "湖北省" },
  { code: "0728", city: "仙桃市", province: "湖北省" },

  // 湖南
  { code: "0731", city: "长沙市", province: "湖南省" },
  { code: "0730", city: "岳阳市", province: "湖南省" },
  { code: "0732", city: "湘潭市", province: "湖南省" },
  { code: "0733", city: "株洲市", province: "湖南省" },
  { code: "0734", city: "衡阳市", province: "湖南省" },
  { code: "0735", city: "郴州市", province: "湖南省" },
  { code: "0736", city: "常德市", province: "湖南省" },
  { code: "0737", city: "益阳市", province: "湖南省" },
  { code: "0738", city: "娄底市", province: "湖南省" },
  { code: "0739", city: "邵阳市", province: "湖南省" },
  { code: "0743", city: "湘西土家族苗族自治州", province: "湖南省" },
  { code: "0744", city: "张家界市", province: "湖南省" },
  { code: "0745", city: "怀化市", province: "湖南省" },
  { code: "0746", city: "永州市", province: "湖南省" },

  // 广东
  { code: "020", city: "广州市", province: "广东省" },
  { code: "0755", city: "深圳市", province: "广东省" },
  { code: "0750", city: "江门市", province: "广东省" },
  { code: "0751", city: "韶关市", province: "广东省" },
  { code: "0752", city: "惠州市", province: "广东省" },
  { code: "0753", city: "梅州市", province: "广东省" },
  { code: "0754", city: "汕头市", province: "广东省" },
  { code: "0756", city: "珠海市", province: "广东省" },
  { code: "0757", city: "佛山市", province: "广东省" },
  { code: "0758", city: "肇庆市", province: "广东省" },
  { code: "0759", city: "湛江市", province: "广东省" },
  { code: "0760", city: "中山市", province: "广东省" },
  { code: "0762", city: "河源市", province: "广东省" },
  { code: "0763", city: "清远市", province: "广东省" },
  { code: "0765", city: "顺德市", province: "广东省" },
  { code: "0766", city: "云浮市", province: "广东省" },
  { code: "0768", city: "潮州市", province: "广东省" },
  { code: "0769", city: "东莞市", province: "广东省" },
  { code: "0770", city: "防城港市", province: "广西壮族自治区" },
  { code: "0662", city: "阳江市", province: "广东省" },
  { code: "0660", city: "汕尾市", province: "广东省" },
  { code: "0668", city: "茂名市", province: "广东省" },
  { code: "0750", city: "鹤山市", province: "广东省" },

  // 广西
  { code: "0771", city: "南宁市", province: "广西壮族自治区" },
  { code: "0772", city: "柳州市", province: "广西壮族自治区" },
  { code: "0773", city: "桂林市", province: "广西壮族自治区" },
  { code: "0774", city: "梧州市", province: "广西壮族自治区" },
  { code: "0775", city: "玉林市", province: "广西壮族自治区" },
  { code: "0776", city: "百色市", province: "广西壮族自治区" },
  { code: "0777", city: "钦州市", province: "广西壮族自治区" },
  { code: "0778", city: "河池市", province: "广西壮族自治区" },
  { code: "0779", city: "北海市", province: "广西壮族自治区" },
  { code: "0770", city: "防城港市", province: "广西壮族自治区" },
  { code: "0762", city: "贺州市", province: "广西壮族自治区" },
  { code: "0772", city: "来宾市", province: "广西壮族自治区" },
  { code: "0771", city: "崇左市", province: "广西壮族自治区" },
  { code: "0775", city: "贵港市", province: "广西壮族自治区" },

  // 海南
  { code: "0898", city: "海口市", province: "海南省" },
  { code: "0898", city: "三亚市", province: "海南省" },
  { code: "0898", city: "儋州市", province: "海南省" },

  // 四川
  { code: "028", city: "成都市", province: "四川省" },
  { code: "0812", city: "攀枝花市", province: "四川省" },
  { code: "0813", city: "自贡市", province: "四川省" },
  { code: "0816", city: "绵阳市", province: "四川省" },
  { code: "0817", city: "南充市", province: "四川省" },
  { code: "0818", city: "达州市", province: "四川省" },
  { code: "0825", city: "遂宁市", province: "四川省" },
  { code: "0826", city: "广安市", province: "四川省" },
  { code: "0827", city: "巴中市", province: "四川省" },
  { code: "0830", city: "泸州市", province: "四川省" },
  { code: "0831", city: "宜宾市", province: "四川省" },
  { code: "0832", city: "内江市", province: "四川省" },
  { code: "0833", city: "乐山市", province: "四川省" },
  { code: "0834", city: "凉山彝族自治州", province: "四川省" },
  { code: "0835", city: "雅安市", province: "四川省" },
  { code: "0836", city: "甘孜藏族自治州", province: "四川省" },
  { code: "0837", city: "阿坝藏族羌族自治州", province: "四川省" },
  { code: "0838", city: "德阳市", province: "四川省" },
  { code: "0839", city: "广元市", province: "四川省" },
  { code: "0825", city: "资阳市", province: "四川省" },
  { code: "0816", city: "眉山市", province: "四川省" },

  // 贵州
  { code: "0851", city: "贵阳市", province: "贵州省" },
  { code: "0852", city: "遵义市", province: "贵州省" },
  { code: "0853", city: "安顺市", province: "贵州省" },
  { code: "0854", city: "黔南布依族苗族自治州", province: "贵州省" },
  { code: "0855", city: "黔东南苗族侗族自治州", province: "贵州省" },
  { code: "0856", city: "铜仁市", province: "贵州省" },
  { code: "0857", city: "毕节市", province: "贵州省" },
  { code: "0858", city: "六盘水市", province: "贵州省" },
  { code: "0859", city: "黔西南布依族苗族自治州", province: "贵州省" },

  // 云南
  { code: "0871", city: "昆明市", province: "云南省" },
  { code: "0872", city: "大理白族自治州", province: "云南省" },
  { code: "0873", city: "红河哈尼族彝族自治州", province: "云南省" },
  { code: "0874", city: "曲靖市", province: "云南省" },
  { code: "0875", city: "保山市", province: "云南省" },
  { code: "0876", city: "文山壮族苗族自治州", province: "云南省" },
  { code: "0877", city: "玉溪市", province: "云南省" },
  { code: "0878", city: "楚雄彝族自治州", province: "云南省" },
  { code: "0879", city: "普洱市", province: "云南省" },
  { code: "0883", city: "临沧市", province: "云南省" },
  { code: "0886", city: "怒江傈僳族自治州", province: "云南省" },
  { code: "0887", city: "迪庆藏族自治州", province: "云南省" },
  { code: "0888", city: "丽江市", province: "云南省" },
  { code: "0691", city: "西双版纳傣族自治州", province: "云南省" },
  { code: "0870", city: "昭通市", province: "云南省" },
  { code: "0883", city: "德宏傣族景颇族自治州", province: "云南省" },

  // 西藏
  { code: "0891", city: "拉萨市", province: "西藏自治区" },
  { code: "0892", city: "日喀则市", province: "西藏自治区" },
  { code: "0893", city: "山南市", province: "西藏自治区" },
  { code: "0894", city: "林芝市", province: "西藏自治区" },
  { code: "0895", city: "昌都市", province: "西藏自治区" },
  { code: "0896", city: "那曲市", province: "西藏自治区" },
  { code: "0897", city: "阿里地区", province: "西藏自治区" },

  // 陕西
  { code: "029", city: "西安市", province: "陕西省" },
  { code: "0911", city: "延安市", province: "陕西省" },
  { code: "0912", city: "榆林市", province: "陕西省" },
  { code: "0913", city: "渭南市", province: "陕西省" },
  { code: "0914", city: "商洛市", province: "陕西省" },
  { code: "0915", city: "安康市", province: "陕西省" },
  { code: "0916", city: "汉中市", province: "陕西省" },
  { code: "0917", city: "宝鸡市", province: "陕西省" },
  { code: "0919", city: "铜川市", province: "陕西省" },

  // 甘肃
  { code: "0931", city: "兰州市", province: "甘肃省" },
  { code: "0932", city: "定西市", province: "甘肃省" },
  { code: "0933", city: "平凉市", province: "甘肃省" },
  { code: "0934", city: "庆阳市", province: "甘肃省" },
  { code: "0935", city: "武威市", province: "甘肃省" },
  { code: "0936", city: "张掖市", province: "甘肃省" },
  { code: "0937", city: "酒泉市", province: "甘肃省" },
  { code: "0938", city: "天水市", province: "甘肃省" },
  { code: "0939", city: "陇南市", province: "甘肃省" },
  { code: "0941", city: "甘南藏族自治州", province: "甘肃省" },
  { code: "0943", city: "白银市", province: "甘肃省" },
  { code: "0935", city: "金昌市", province: "甘肃省" },
  { code: "0937", city: "嘉峪关市", province: "甘肃省" },
  { code: "0930", city: "临夏回族自治州", province: "甘肃省" },

  // 青海
  { code: "0971", city: "西宁市", province: "青海省" },
  { code: "0972", city: "海东市", province: "青海省" },
  { code: "0973", city: "黄南藏族自治州", province: "青海省" },
  { code: "0974", city: "海南藏族自治州", province: "青海省" },
  { code: "0975", city: "果洛藏族自治州", province: "青海省" },
  { code: "0976", city: "玉树藏族自治州", province: "青海省" },
  { code: "0977", city: "海西蒙古族藏族自治州", province: "青海省" },
  { code: "0970", city: "海北藏族自治州", province: "青海省" },

  // 宁夏
  { code: "0951", city: "银川市", province: "宁夏回族自治区" },
  { code: "0952", city: "石嘴山市", province: "宁夏回族自治区" },
  { code: "0953", city: "吴忠市", province: "宁夏回族自治区" },
  { code: "0954", city: "固原市", province: "宁夏回族自治区" },
  { code: "0955", city: "中卫市", province: "宁夏回族自治区" },

  // 新疆
  { code: "0991", city: "乌鲁木齐市", province: "新疆维吾尔自治区" },
  { code: "0992", city: "奎屯市", province: "新疆维吾尔自治区" },
  { code: "0993", city: "石河子市", province: "新疆维吾尔自治区" },
  { code: "0994", city: "昌吉回族自治州", province: "新疆维吾尔自治区" },
  { code: "0995", city: "吐鲁番市", province: "新疆维吾尔自治区" },
  { code: "0996", city: "巴音郭楞蒙古自治州", province: "新疆维吾尔自治区" },
  { code: "0997", city: "阿克苏地区", province: "新疆维吾尔自治区" },
  { code: "0998", city: "喀什地区", province: "新疆维吾尔自治区" },
  { code: "0999", city: "伊犁哈萨克自治州", province: "新疆维吾尔自治区" },
  { code: "0901", city: "阿勒泰地区", province: "新疆维吾尔自治区" },
  { code: "0902", city: "哈密市", province: "新疆维吾尔自治区" },
  { code: "0903", city: "和田地区", province: "新疆维吾尔自治区" },
  { code: "0906", city: "塔城地区", province: "新疆维吾尔自治区" },
  { code: "0908", city: "博尔塔拉蒙古自治州", province: "新疆维吾尔自治区" },
  { code: "0909", city: "克拉玛依市", province: "新疆维吾尔自治区" },
  { code: "0903", city: "克孜勒苏柯尔克孜自治州", province: "新疆维吾尔自治区" },

  // 内蒙古
  { code: "0471", city: "呼和浩特市", province: "内蒙古自治区" },
  { code: "0472", city: "包头市", province: "内蒙古自治区" },
  { code: "0473", city: "乌海市", province: "内蒙古自治区" },
  { code: "0474", city: "集宁市", province: "内蒙古自治区" },
  { code: "0475", city: "通辽市", province: "内蒙古自治区" },
  { code: "0476", city: "赤峰市", province: "内蒙古自治区" },
  { code: "0477", city: "鄂尔多斯市", province: "内蒙古自治区" },
  { code: "0478", city: "巴彦淖尔市", province: "内蒙古自治区" },
  { code: "0479", city: "锡林郭勒盟", province: "内蒙古自治区" },
  { code: "0470", city: "呼伦贝尔市", province: "内蒙古自治区" },
  { code: "0482", city: "兴安盟", province: "内蒙古自治区" },
  { code: "0483", city: "阿拉善盟", province: "内蒙古自治区" },
];

export function lookupByCode(code: string): AreaCodeEntry[] {
  const c = code.trim();
  if (c === "") return [];
  return AREA_CODES.filter((e) => e.code === c);
}

export function lookupByCity(city: string): AreaCodeEntry[] {
  const q = city.trim();
  if (q === "") return [];
  return AREA_CODES.filter((e) => e.city.includes(q) || e.province.includes(q));
}
