// 医院推荐 — 知名医院数据（name + province + city + level + departments + intro）。

export interface Hospital {
  name: string;
  province: string;
  city: string;
  level: string;
  keyDepts: string[];
  intro: string;
}

export const HOSPITALS: Hospital[] = [
  { name: "北京协和医院", province: "北京", city: "北京", level: "三级甲等", keyDepts: ["内科", "外科", "妇产科", "眼科", "骨科", "神经内科"], intro: "中国医学科学院北京协和医院，综合实力全国顶尖。" },
  { name: "北京大学第一医院", province: "北京", city: "北京", level: "三级甲等", keyDepts: ["内科", "外科", "泌尿外科", "肾脏内科", "妇产科"], intro: "北大医院，泌尿外科、肾脏内科为优势学科。" },
  { name: "北京大学第三医院", province: "北京", city: "北京", level: "三级甲等", keyDepts: ["骨科", "生殖医学", "运动医学", "内科"], intro: "北医三院，骨科与生殖医学中心闻名。" },
  { name: "北京大学人民医院", province: "北京", city: "北京", level: "三级甲等", keyDepts: ["血液科", "胸外科", "眼科", "心血管内科"], intro: "北大人民医院，血液病诊疗为优势。" },
  { name: "中国人民解放军总医院（301医院）", province: "北京", city: "北京", level: "三级甲等", keyDepts: ["耳鼻喉科", "肝胆外科", "骨科", "内科"], intro: "解放军总医院，综合实力雄厚。" },
  { name: "北京天坛医院", province: "北京", city: "北京", level: "三级甲等", keyDepts: ["神经内科", "神经外科", "神经影像"], intro: "以神经科学为核心的综合性医院。" },
  { name: "北京同仁医院", province: "北京", city: "北京", level: "三级甲等", keyDepts: ["眼科", "耳鼻喉科", "心血管内科"], intro: "眼科与耳鼻喉科全国领先。" },
  { name: "中国医学科学院阜外医院", province: "北京", city: "北京", level: "三级甲等", keyDepts: ["心血管内科", "心血管外科"], intro: "心血管病专科医院，全国权威。" },
  { name: "北京儿童医院", province: "北京", city: "北京", level: "三级甲等", keyDepts: ["儿科", "小儿外科", "新生儿科"], intro: "首都医科大学附属北京儿童医院。" },
  { name: "上海瑞金医院", province: "上海", city: "上海", level: "三级甲等", keyDepts: ["内分泌科", "血液科", "烧伤科", "心血管内科"], intro: "上海交通大学医学院附属瑞金医院。" },
  { name: "上海中山医院", province: "上海", city: "上海", level: "三级甲等", keyDepts: ["心血管内科", "肝外科", "呼吸内科"], intro: "复旦大学附属中山医院，综合实力强。" },
  { name: "上海华山医院", province: "上海", city: "上海", level: "三级甲等", keyDepts: ["神经内科", "皮肤科", "手外科", "感染科"], intro: "复旦大学附属华山医院，神经科与皮肤科闻名。" },
  { name: "上海长海医院", province: "上海", city: "上海", level: "三级甲等", keyDepts: ["消化内科", "胸心外科", "烧伤科"], intro: "海军军医大学附属长海医院。" },
  { name: "上海仁济医院", province: "上海", city: "上海", level: "三级甲等", keyDepts: ["消化内科", "风湿免疫科", "生殖医学"], intro: "上海交通大学医学院附属仁济医院。" },
  { name: "上海第九人民医院", province: "上海", city: "上海", level: "三级甲等", keyDepts: ["口腔科", "整形外科", "骨科"], intro: "上海九院，口腔颌面外科与整形外科闻名。" },
  { name: "上海儿童医学中心", province: "上海", city: "上海", level: "三级甲等", keyDepts: ["儿科", "心胸外科", "血液肿瘤科"], intro: "上海交通大学医学院附属上海儿童医学中心。" },
  { name: "复旦大学附属肿瘤医院", province: "上海", city: "上海", level: "三级甲等", keyDepts: ["肿瘤科", "放疗科", "病理科"], intro: "上海肿瘤医院，肿瘤诊疗权威。" },
  { name: "广东省人民医院", province: "广东", city: "广州", level: "三级甲等", keyDepts: ["心血管内科", "心外科", "肿瘤科"], intro: "广东省人民医院，心血管病研究所闻名。" },
  { name: "中山大学附属第一医院", province: "广东", city: "广州", level: "三级甲等", keyDepts: ["内科", "外科", "器官移植", "妇产科"], intro: "中山一院，华南综合实力顶尖。" },
  { name: "中山大学孙逸仙纪念医院", province: "广东", city: "广州", level: "三级甲等", keyDepts: ["泌尿外科", "骨外科", "内分泌科"], intro: "中山二院，历史悠久的西医院。" },
  { name: "南方医科大学南方医院", province: "广东", city: "广州", level: "三级甲等", keyDepts: ["消化内科", "肾内科", "创伤骨科"], intro: "南方医院，传染病与消化内科为优势。" },
  { name: "广州市妇女儿童医疗中心", province: "广东", city: "广州", level: "三级甲等", keyDepts: ["儿科", "妇产科", "小儿外科"], intro: "广州妇儿中心，妇幼健康专科。" },
  { name: "深圳市人民医院", province: "广东", city: "深圳", level: "三级甲等", keyDepts: ["内科", "外科", "急诊科"], intro: "深圳规模最大的综合性医院。" },
  { name: "浙江大学医学院附属第一医院", province: "浙江", city: "杭州", level: "三级甲等", keyDepts: ["传染病科", "肝胆胰外科", "血液病科"], intro: "浙大一院，传染病与肝胆胰外科为优势。" },
  { name: "浙江大学医学院附属第二医院", province: "浙江", city: "杭州", level: "三级甲等", keyDepts: ["心血管内科", "神经内科", "急诊科"], intro: "浙大二院，急诊与心脑血管疾病为优势。" },
  { name: "浙江大学医学院附属邵逸夫医院", province: "浙江", city: "杭州", level: "三级甲等", keyDepts: ["内科", "外科", "肿瘤内科"], intro: "邵逸夫医院，管理与服务闻名。" },
  { name: "江苏省人民医院", province: "江苏", city: "南京", level: "三级甲等", keyDepts: ["心血管内科", "肝脏外科", "康复科"], intro: "南京医科大学第一附属医院。" },
  { name: "南京鼓楼医院", province: "江苏", city: "南京", level: "三级甲等", keyDepts: ["骨科", "免疫科", "生殖医学"], intro: "南京大学医学院附属鼓楼医院。" },
  { name: "苏州大学附属第一医院", province: "江苏", city: "苏州", level: "三级甲等", keyDepts: ["血液科", "骨科", "神经外科"], intro: "苏大附一院，血液病诊疗为优势。" },
  { name: "四川大学华西医院", province: "四川", city: "成都", level: "三级甲等", keyDepts: ["麻醉科", "普外科", "胸外科", "神经内科"], intro: "华西医院，综合实力全国前列。" },
  { name: "四川省人民医院", province: "四川", city: "成都", level: "三级甲等", keyDepts: ["内科", "外科", "眼科"], intro: "四川省人民医院。" },
  { name: "华中科技大学同济医学院附属同济医院", province: "湖北", city: "武汉", level: "三级甲等", keyDepts: ["妇产科", "心血管内科", "器官移植"], intro: "武汉同济医院，器官移植与妇产闻名。" },
  { name: "华中科技大学同济医学院附属协和医院", province: "湖北", city: "武汉", level: "三级甲等", keyDepts: ["心血管外科", "血液科", "耳鼻喉科"], intro: "武汉协和医院。" },
  { name: "中南大学湘雅医院", province: "湖南", city: "长沙", level: "三级甲等", keyDepts: ["神经内科", "骨科", "内科"], intro: "湘雅医院，百年名院。" },
  { name: "中南大学湘雅二医院", province: "湖南", city: "长沙", level: "三级甲等", keyDepts: ["精神科", "内分泌科", "心血管内科"], intro: "湘雅二医院，精神心理学科为优势。" },
  { name: "山东大学齐鲁医院", province: "山东", city: "济南", level: "三级甲等", keyDepts: ["内科", "神经内科", "耳鼻喉科"], intro: "齐鲁医院，百年名院。" },
  { name: "青岛大学附属医院", province: "山东", city: "青岛", level: "三级甲等", keyDepts: ["眼科", "内科", "外科"], intro: "青大附院。" },
  { name: "西安交通大学第一附属医院", province: "陕西", city: "西安", level: "三级甲等", keyDepts: ["内科", "外科", "心血管内科"], intro: "西安交大一附院。" },
  { name: "空军军医大学西京医院", province: "陕西", city: "西安", level: "三级甲等", keyDepts: ["消化内科", "骨科", "整形外科"], intro: "西京医院，综合实力强。" },
  { name: "天津医科大学总医院", province: "天津", city: "天津", level: "三级甲等", keyDepts: ["神经内科", "内科", "外科"], intro: "天津医大总医院。" },
  { name: "中国医学科学院血液病医院", province: "天津", city: "天津", level: "三级甲等", keyDepts: ["血液科"], intro: "血液病专科权威。" },
  { name: "重庆医科大学附属第一医院", province: "重庆", city: "重庆", level: "三级甲等", keyDepts: ["神经内科", "内科", "外科"], intro: "重医附一院。" },
  { name: "陆军军医大学西南医院", province: "重庆", city: "重庆", level: "三级甲等", keyDepts: ["烧伤科", "感染科", "骨科"], intro: "西南医院，烧伤科全国闻名。" },
  { name: "吉林大学第一医院", province: "吉林", city: "长春", level: "三级甲等", keyDepts: ["内科", "外科", "神经内科"], intro: "吉大一院。" },
  { name: "哈尔滨医科大学附属第一医院", province: "黑龙江", city: "哈尔滨", level: "三级甲等", keyDepts: ["心血管内科", "神经外科", "内科"], intro: "哈医大一院。" },
  { name: "中国医科大学附属第一医院", province: "辽宁", city: "沈阳", level: "三级甲等", keyDepts: ["呼吸内科", "内分泌科", "内科"], intro: "中国医大一院。" },
  { name: "大连医科大学附属第一医院", province: "辽宁", city: "大连", level: "三级甲等", keyDepts: ["内科", "外科", "心内科"], intro: "大医一院。" },
  { name: "福建医科大学附属协和医院", province: "福建", city: "福州", level: "三级甲等", keyDepts: ["血液科", "心血管内科", "胸外科"], intro: "福建协和医院。" },
  { name: "福建省立医院", province: "福建", city: "福州", level: "三级甲等", keyDepts: ["心血管内科", "内科", "急诊科"], intro: "福建省立医院。" },
  { name: "南昌大学第一附属医院", province: "江西", city: "南昌", level: "三级甲等", keyDepts: ["内科", "外科", "眼科"], intro: "南大一附院。" },
  { name: "郑州大学第一附属医院", province: "河南", city: "郑州", level: "三级甲等", keyDepts: ["内科", "外科", "器官移植"], intro: "郑大一附院，规模最大的医院之一。" },
  { name: "河北省人民医院", province: "河北", city: "石家庄", level: "三级甲等", keyDepts: ["内科", "外科", "心血管内科"], intro: "河北省人民医院。" },
  { name: "安徽医科大学第一附属医院", province: "安徽", city: "合肥", level: "三级甲等", keyDepts: ["皮肤科", "内科", "外科"], intro: "安医大一附院，皮肤科为优势。" },
  { name: "广西医科大学第一附属医院", province: "广西", city: "南宁", level: "三级甲等", keyDepts: ["内科", "外科", "耳鼻喉科"], intro: "广医一附院。" },
  { name: "昆明医科大学第一附属医院", province: "云南", city: "昆明", level: "三级甲等", keyDepts: ["内科", "外科", "眼科"], intro: "云大医院。" },
  { name: "新疆医科大学第一附属医院", province: "新疆", city: "乌鲁木齐", level: "三级甲等", keyDepts: ["内科", "外科", "心血管内科"], intro: "新医大一附院。" },
  { name: "兰州大学第一医院", province: "甘肃", city: "兰州", level: "三级甲等", keyDepts: ["心血管内科", "内科", "外科"], intro: "兰大一院。" },
  { name: "宁夏医科大学总医院", province: "宁夏", city: "银川", level: "三级甲等", keyDepts: ["内科", "外科", "儿科"], intro: "宁夏医大总医院。" },
  { name: "内蒙古医科大学附属医院", province: "内蒙古", city: "呼和浩特", level: "三级甲等", keyDepts: ["内科", "外科", "蒙医科"], intro: "内蒙古医大附属医院。" },
  { name: "海南省人民医院", province: "海南", city: "海口", level: "三级甲等", keyDepts: ["内科", "外科", "儿科"], intro: "海南省人民医院。" },
  { name: "贵州医科大学附属医院", province: "贵州", city: "贵阳", level: "三级甲等", keyDepts: ["内科", "外科", "神经内科"], intro: "贵医附院。" },
];
