// Country → capital mapping for sovereign states (150+ entries).
// Data covers all major countries and is intended for lookup utilities.

export interface CountryCapital {
  country: string;
  countryEn: string;
  capital: string;
  capitalEn: string;
  region: string;
}

export const CAPITALS: CountryCapital[] = [
  // 亚洲
  { country: "中国", countryEn: "China", capital: "北京", capitalEn: "Beijing", region: "亚洲" },
  { country: "日本", countryEn: "Japan", capital: "东京", capitalEn: "Tokyo", region: "亚洲" },
  { country: "韩国", countryEn: "South Korea", capital: "首尔", capitalEn: "Seoul", region: "亚洲" },
  { country: "朝鲜", countryEn: "North Korea", capital: "平壤", capitalEn: "Pyongyang", region: "亚洲" },
  { country: "蒙古", countryEn: "Mongolia", capital: "乌兰巴托", capitalEn: "Ulaanbaatar", region: "亚洲" },
  { country: "越南", countryEn: "Vietnam", capital: "河内", capitalEn: "Hanoi", region: "亚洲" },
  { country: "老挝", countryEn: "Laos", capital: "万象", capitalEn: "Vientiane", region: "亚洲" },
  { country: "柬埔寨", countryEn: "Cambodia", capital: "金边", capitalEn: "Phnom Penh", region: "亚洲" },
  { country: "泰国", countryEn: "Thailand", capital: "曼谷", capitalEn: "Bangkok", region: "亚洲" },
  { country: "缅甸", countryEn: "Myanmar", capital: "内比都", capitalEn: "Naypyidaw", region: "亚洲" },
  { country: "马来西亚", countryEn: "Malaysia", capital: "吉隆坡", capitalEn: "Kuala Lumpur", region: "亚洲" },
  { country: "新加坡", countryEn: "Singapore", capital: "新加坡", capitalEn: "Singapore", region: "亚洲" },
  { country: "印度尼西亚", countryEn: "Indonesia", capital: "雅加达", capitalEn: "Jakarta", region: "亚洲" },
  { country: "菲律宾", countryEn: "Philippines", capital: "马尼拉", capitalEn: "Manila", region: "亚洲" },
  { country: "文莱", countryEn: "Brunei", capital: "斯里巴加湾市", capitalEn: "Bandar Seri Begawan", region: "亚洲" },
  { country: "东帝汶", countryEn: "East Timor", capital: "帝力", capitalEn: "Dili", region: "亚洲" },
  { country: "印度", countryEn: "India", capital: "新德里", capitalEn: "New Delhi", region: "亚洲" },
  { country: "巴基斯坦", countryEn: "Pakistan", capital: "伊斯兰堡", capitalEn: "Islamabad", region: "亚洲" },
  { country: "孟加拉国", countryEn: "Bangladesh", capital: "达卡", capitalEn: "Dhaka", region: "亚洲" },
  { country: "斯里兰卡", countryEn: "Sri Lanka", capital: "科伦坡", capitalEn: "Colombo", region: "亚洲" },
  { country: "马尔代夫", countryEn: "Maldives", capital: "马累", capitalEn: "Male", region: "亚洲" },
  { country: "尼泊尔", countryEn: "Nepal", capital: "加德满都", capitalEn: "Kathmandu", region: "亚洲" },
  { country: "不丹", countryEn: "Bhutan", capital: "廷布", capitalEn: "Thimphu", region: "亚洲" },
  { country: "阿富汗", countryEn: "Afghanistan", capital: "喀布尔", capitalEn: "Kabul", region: "亚洲" },
  { country: "伊朗", countryEn: "Iran", capital: "德黑兰", capitalEn: "Tehran", region: "亚洲" },
  { country: "伊拉克", countryEn: "Iraq", capital: "巴格达", capitalEn: "Baghdad", region: "亚洲" },
  { country: "科威特", countryEn: "Kuwait", capital: "科威特城", capitalEn: "Kuwait City", region: "亚洲" },
  { country: "沙特阿拉伯", countryEn: "Saudi Arabia", capital: "利雅得", capitalEn: "Riyadh", region: "亚洲" },
  { country: "巴林", countryEn: "Bahrain", capital: "麦纳麦", capitalEn: "Manama", region: "亚洲" },
  { country: "卡塔尔", countryEn: "Qatar", capital: "多哈", capitalEn: "Doha", region: "亚洲" },
  { country: "阿联酋", countryEn: "United Arab Emirates", capital: "阿布扎比", capitalEn: "Abu Dhabi", region: "亚洲" },
  { country: "阿曼", countryEn: "Oman", capital: "马斯喀特", capitalEn: "Muscat", region: "亚洲" },
  { country: "也门", countryEn: "Yemen", capital: "萨那", capitalEn: "Sanaa", region: "亚洲" },
  { country: "约旦", countryEn: "Jordan", capital: "安曼", capitalEn: "Amman", region: "亚洲" },
  { country: "叙利亚", countryEn: "Syria", capital: "大马士革", capitalEn: "Damascus", region: "亚洲" },
  { country: "黎巴嫩", countryEn: "Lebanon", capital: "贝鲁特", capitalEn: "Beirut", region: "亚洲" },
  { country: "以色列", countryEn: "Israel", capital: "耶路撒冷", capitalEn: "Jerusalem", region: "亚洲" },
  { country: "巴勒斯坦", countryEn: "Palestine", capital: "拉马拉", capitalEn: "Ramallah", region: "亚洲" },
  { country: "土耳其", countryEn: "Turkey", capital: "安卡拉", capitalEn: "Ankara", region: "亚洲" },
  { country: "塞浦路斯", countryEn: "Cyprus", capital: "尼科西亚", capitalEn: "Nicosia", region: "亚洲" },
  { country: "哈萨克斯坦", countryEn: "Kazakhstan", capital: "阿斯塔纳", capitalEn: "Astana", region: "亚洲" },
  { country: "乌兹别克斯坦", countryEn: "Uzbekistan", capital: "塔什干", capitalEn: "Tashkent", region: "亚洲" },
  { country: "土库曼斯坦", countryEn: "Turkmenistan", capital: "阿什哈巴德", capitalEn: "Ashgabat", region: "亚洲" },
  { country: "吉尔吉斯斯坦", countryEn: "Kyrgyzstan", capital: "比什凯克", capitalEn: "Bishkek", region: "亚洲" },
  { country: "塔吉克斯坦", countryEn: "Tajikistan", capital: "杜尚别", capitalEn: "Dushanbe", region: "亚洲" },

  // 欧洲
  { country: "英国", countryEn: "United Kingdom", capital: "伦敦", capitalEn: "London", region: "欧洲" },
  { country: "法国", countryEn: "France", capital: "巴黎", capitalEn: "Paris", region: "欧洲" },
  { country: "德国", countryEn: "Germany", capital: "柏林", capitalEn: "Berlin", region: "欧洲" },
  { country: "意大利", countryEn: "Italy", capital: "罗马", capitalEn: "Rome", region: "欧洲" },
  { country: "西班牙", countryEn: "Spain", capital: "马德里", capitalEn: "Madrid", region: "欧洲" },
  { country: "葡萄牙", countryEn: "Portugal", capital: "里斯本", capitalEn: "Lisbon", region: "欧洲" },
  { country: "荷兰", countryEn: "Netherlands", capital: "阿姆斯特丹", capitalEn: "Amsterdam", region: "欧洲" },
  { country: "比利时", countryEn: "Belgium", capital: "布鲁塞尔", capitalEn: "Brussels", region: "欧洲" },
  { country: "卢森堡", countryEn: "Luxembourg", capital: "卢森堡市", capitalEn: "Luxembourg City", region: "欧洲" },
  { country: "瑞士", countryEn: "Switzerland", capital: "伯尔尼", capitalEn: "Bern", region: "欧洲" },
  { country: "奥地利", countryEn: "Austria", capital: "维也纳", capitalEn: "Vienna", region: "欧洲" },
  { country: "列支敦士登", countryEn: "Liechtenstein", capital: "瓦杜兹", capitalEn: "Vaduz", region: "欧洲" },
  { country: "爱尔兰", countryEn: "Ireland", capital: "都柏林", capitalEn: "Dublin", region: "欧洲" },
  { country: "冰岛", countryEn: "Iceland", capital: "雷克雅未克", capitalEn: "Reykjavik", region: "欧洲" },
  { country: "丹麦", countryEn: "Denmark", capital: "哥本哈根", capitalEn: "Copenhagen", region: "欧洲" },
  { country: "挪威", countryEn: "Norway", capital: "奥斯陆", capitalEn: "Oslo", region: "欧洲" },
  { country: "瑞典", countryEn: "Sweden", capital: "斯德哥尔摩", capitalEn: "Stockholm", region: "欧洲" },
  { country: "芬兰", countryEn: "Finland", capital: "赫尔辛基", capitalEn: "Helsinki", region: "欧洲" },
  { country: "爱沙尼亚", countryEn: "Estonia", capital: "塔林", capitalEn: "Tallinn", region: "欧洲" },
  { country: "拉脱维亚", countryEn: "Latvia", capital: "里加", capitalEn: "Riga", region: "欧洲" },
  { country: "立陶宛", countryEn: "Lithuania", capital: "维尔纽斯", capitalEn: "Vilnius", region: "欧洲" },
  { country: "波兰", countryEn: "Poland", capital: "华沙", capitalEn: "Warsaw", region: "欧洲" },
  { country: "捷克", countryEn: "Czech Republic", capital: "布拉格", capitalEn: "Prague", region: "欧洲" },
  { country: "斯洛伐克", countryEn: "Slovakia", capital: "布拉迪斯拉发", capitalEn: "Bratislava", region: "欧洲" },
  { country: "匈牙利", countryEn: "Hungary", capital: "布达佩斯", capitalEn: "Budapest", region: "欧洲" },
  { country: "罗马尼亚", countryEn: "Romania", capital: "布加勒斯特", capitalEn: "Bucharest", region: "欧洲" },
  { country: "保加利亚", countryEn: "Bulgaria", capital: "索非亚", capitalEn: "Sofia", region: "欧洲" },
  { country: "希腊", countryEn: "Greece", capital: "雅典", capitalEn: "Athens", region: "欧洲" },
  { country: "阿尔巴尼亚", countryEn: "Albania", capital: "地拉那", capitalEn: "Tirana", region: "欧洲" },
  { country: "塞尔维亚", countryEn: "Serbia", capital: "贝尔格莱德", capitalEn: "Belgrade", region: "欧洲" },
  { country: "克罗地亚", countryEn: "Croatia", capital: "萨格勒布", capitalEn: "Zagreb", region: "欧洲" },
  { country: "斯洛文尼亚", countryEn: "Slovenia", capital: "卢布尔雅那", capitalEn: "Ljubljana", region: "欧洲" },
  { country: "波黑", countryEn: "Bosnia and Herzegovina", capital: "萨拉热窝", capitalEn: "Sarajevo", region: "欧洲" },
  { country: "黑山", countryEn: "Montenegro", capital: "波德戈里察", capitalEn: "Podgorica", region: "欧洲" },
  { country: "北马其顿", countryEn: "North Macedonia", capital: "斯科普里", capitalEn: "Skopje", region: "欧洲" },
  { country: "摩尔多瓦", countryEn: "Moldova", capital: "基希讷乌", capitalEn: "Chisinau", region: "欧洲" },
  { country: "乌克兰", countryEn: "Ukraine", capital: "基辅", capitalEn: "Kyiv", region: "欧洲" },
  { country: "白俄罗斯", countryEn: "Belarus", capital: "明斯克", capitalEn: "Minsk", region: "欧洲" },
  { country: "俄罗斯", countryEn: "Russia", capital: "莫斯科", capitalEn: "Moscow", region: "欧洲" },
  { country: "梵蒂冈", countryEn: "Vatican City", capital: "梵蒂冈城", capitalEn: "Vatican City", region: "欧洲" },
  { country: "摩纳哥", countryEn: "Monaco", capital: "摩纳哥城", capitalEn: "Monaco", region: "欧洲" },
  { country: "安道尔", countryEn: "Andorra", capital: "安道尔城", capitalEn: "Andorra la Vella", region: "欧洲" },
  { country: "圣马力诺", countryEn: "San Marino", capital: "圣马力诺市", capitalEn: "San Marino", region: "欧洲" },
  { country: "马耳他", countryEn: "Malta", capital: "瓦莱塔", capitalEn: "Valletta", region: "欧洲" },

  // 非洲
  { country: "埃及", countryEn: "Egypt", capital: "开罗", capitalEn: "Cairo", region: "非洲" },
  { country: "利比亚", countryEn: "Libya", capital: "的黎波里", capitalEn: "Tripoli", region: "非洲" },
  { country: "突尼斯", countryEn: "Tunisia", capital: "突尼斯市", capitalEn: "Tunis", region: "非洲" },
  { country: "阿尔及利亚", countryEn: "Algeria", capital: "阿尔及尔", capitalEn: "Algiers", region: "非洲" },
  { country: "摩洛哥", countryEn: "Morocco", capital: "拉巴特", capitalEn: "Rabat", region: "非洲" },
  { country: "苏丹", countryEn: "Sudan", capital: "喀土穆", capitalEn: "Khartoum", region: "非洲" },
  { country: "南苏丹", countryEn: "South Sudan", capital: "朱巴", capitalEn: "Juba", region: "非洲" },
  { country: "埃塞俄比亚", countryEn: "Ethiopia", capital: "亚的斯亚贝巴", capitalEn: "Addis Ababa", region: "非洲" },
  { country: "厄立特里亚", countryEn: "Eritrea", capital: "阿斯马拉", capitalEn: "Asmara", region: "非洲" },
  { country: "吉布提", countryEn: "Djibouti", capital: "吉布提市", capitalEn: "Djibouti", region: "非洲" },
  { country: "索马里", countryEn: "Somalia", capital: "摩加迪沙", capitalEn: "Mogadishu", region: "非洲" },
  { country: "肯尼亚", countryEn: "Kenya", capital: "内罗毕", capitalEn: "Nairobi", region: "非洲" },
  { country: "乌干达", countryEn: "Uganda", capital: "坎帕拉", capitalEn: "Kampala", region: "非洲" },
  { country: "坦桑尼亚", countryEn: "Tanzania", capital: "多多马", capitalEn: "Dodoma", region: "非洲" },
  { country: "卢旺达", countryEn: "Rwanda", capital: "基加利", capitalEn: "Kigali", region: "非洲" },
  { country: "布隆迪", countryEn: "Burundi", capital: "基特加", capitalEn: "Gitega", region: "非洲" },
  { country: "塞内加尔", countryEn: "Senegal", capital: "达喀尔", capitalEn: "Dakar", region: "非洲" },
  { country: "冈比亚", countryEn: "Gambia", capital: "班珠尔", capitalEn: "Banjul", region: "非洲" },
  { country: "马里", countryEn: "Mali", capital: "巴马科", capitalEn: "Bamako", region: "非洲" },
  { country: "布基纳法索", countryEn: "Burkina Faso", capital: "瓦加杜古", capitalEn: "Ouagadougou", region: "非洲" },
  { country: "尼日尔", countryEn: "Niger", capital: "尼亚美", capitalEn: "Niamey", region: "非洲" },
  { country: "尼日利亚", countryEn: "Nigeria", capital: "阿布贾", capitalEn: "Abuja", region: "非洲" },
  { country: "加纳", countryEn: "Ghana", capital: "阿克拉", capitalEn: "Accra", region: "非洲" },
  { country: "科特迪瓦", countryEn: "Ivory Coast", capital: "亚穆苏克罗", capitalEn: "Yamoussoukro", region: "非洲" },
  { country: "利比里亚", countryEn: "Liberia", capital: "蒙罗维亚", capitalEn: "Monrovia", region: "非洲" },
  { country: "塞拉利昂", countryEn: "Sierra Leone", capital: "弗里敦", capitalEn: "Freetown", region: "非洲" },
  { country: "几内亚", countryEn: "Guinea", capital: "科纳克里", capitalEn: "Conakry", region: "非洲" },
  { country: "几内亚比绍", countryEn: "Guinea-Bissau", capital: "比绍", capitalEn: "Bissau", region: "非洲" },
  { country: "佛得角", countryEn: "Cape Verde", capital: "普拉亚", capitalEn: "Praia", region: "非洲" },
  { country: "多哥", countryEn: "Togo", capital: "洛美", capitalEn: "Lome", region: "非洲" },
  { country: "贝宁", countryEn: "Benin", capital: "波多诺伏", capitalEn: "Porto-Novo", region: "非洲" },
  { country: "喀麦隆", countryEn: "Cameroon", capital: "雅温得", capitalEn: "Yaounde", region: "非洲" },
  { country: "中非", countryEn: "Central African Republic", capital: "班吉", capitalEn: "Bangui", region: "非洲" },
  { country: "乍得", countryEn: "Chad", capital: "恩贾梅纳", capitalEn: "N'Djamena", region: "非洲" },
  { country: "刚果（布）", countryEn: "Republic of the Congo", capital: "布拉柴维尔", capitalEn: "Brazzaville", region: "非洲" },
  { country: "刚果（金）", countryEn: "Democratic Republic of the Congo", capital: "金沙萨", capitalEn: "Kinshasa", region: "非洲" },
  { country: "加蓬", countryEn: "Gabon", capital: "利伯维尔", capitalEn: "Libreville", region: "非洲" },
  { country: "安哥拉", countryEn: "Angola", capital: "罗安达", capitalEn: "Luanda", region: "非洲" },
  { country: "赞比亚", countryEn: "Zambia", capital: "卢萨卡", capitalEn: "Lusaka", region: "非洲" },
  { country: "津巴布韦", countryEn: "Zimbabwe", capital: "哈拉雷", capitalEn: "Harare", region: "非洲" },
  { country: "马拉维", countryEn: "Malawi", capital: "利隆圭", capitalEn: "Lilongwe", region: "非洲" },
  { country: "莫桑比克", countryEn: "Mozambique", capital: "马普托", capitalEn: "Maputo", region: "非洲" },
  { country: "博茨瓦纳", countryEn: "Botswana", capital: "哈博罗内", capitalEn: "Gaborone", region: "非洲" },
  { country: "纳米比亚", countryEn: "Namibia", capital: "温得和克", capitalEn: "Windhoek", region: "非洲" },
  { country: "南非", countryEn: "South Africa", capital: "比勒陀利亚", capitalEn: "Pretoria", region: "非洲" },
  { country: "莱索托", countryEn: "Lesotho", capital: "马塞卢", capitalEn: "Maseru", region: "非洲" },
  { country: "斯威士兰", countryEn: "Eswatini", capital: "姆巴巴内", capitalEn: "Mbabane", region: "非洲" },
  { country: "马达加斯加", countryEn: "Madagascar", capital: "塔那那利佛", capitalEn: "Antananarivo", region: "非洲" },
  { country: "毛里求斯", countryEn: "Mauritius", capital: "路易港", capitalEn: "Port Louis", region: "非洲" },
  { country: "科摩罗", countryEn: "Comoros", capital: "莫罗尼", capitalEn: "Moroni", region: "非洲" },

  // 北美洲
  { country: "美国", countryEn: "United States", capital: "华盛顿", capitalEn: "Washington, D.C.", region: "北美洲" },
  { country: "加拿大", countryEn: "Canada", capital: "渥太华", capitalEn: "Ottawa", region: "北美洲" },
  { country: "墨西哥", countryEn: "Mexico", capital: "墨西哥城", capitalEn: "Mexico City", region: "北美洲" },
  { country: "危地马拉", countryEn: "Guatemala", capital: "危地马拉市", capitalEn: "Guatemala City", region: "北美洲" },
  { country: "伯利兹", countryEn: "Belize", capital: "贝尔莫潘", capitalEn: "Belmopan", region: "北美洲" },
  { country: "洪都拉斯", countryEn: "Honduras", capital: "特古西加尔巴", capitalEn: "Tegucigalpa", region: "北美洲" },
  { country: "萨尔瓦多", countryEn: "El Salvador", capital: "圣萨尔瓦多", capitalEn: "San Salvador", region: "北美洲" },
  { country: "尼加拉瓜", countryEn: "Nicaragua", capital: "马那瓜", capitalEn: "Managua", region: "北美洲" },
  { country: "哥斯达黎加", countryEn: "Costa Rica", capital: "圣何塞", capitalEn: "San Jose", region: "北美洲" },
  { country: "巴拿马", countryEn: "Panama", capital: "巴拿马城", capitalEn: "Panama City", region: "北美洲" },
  { country: "古巴", countryEn: "Cuba", capital: "哈瓦那", capitalEn: "Havana", region: "北美洲" },
  { country: "牙买加", countryEn: "Jamaica", capital: "金斯敦", capitalEn: "Kingston", region: "北美洲" },
  { country: "海地", countryEn: "Haiti", capital: "太子港", capitalEn: "Port-au-Prince", region: "北美洲" },
  { country: "多米尼加", countryEn: "Dominican Republic", capital: "圣多明各", capitalEn: "Santo Domingo", region: "北美洲" },
  { country: "巴哈马", countryEn: "Bahamas", capital: "拿骚", capitalEn: "Nassau", region: "北美洲" },
  { country: "特立尼达和多巴哥", countryEn: "Trinidad and Tobago", capital: "西班牙港", capitalEn: "Port of Spain", region: "北美洲" },

  // 南美洲
  { country: "哥伦比亚", countryEn: "Colombia", capital: "波哥大", capitalEn: "Bogota", region: "南美洲" },
  { country: "委内瑞拉", countryEn: "Venezuela", capital: "加拉加斯", capitalEn: "Caracas", region: "南美洲" },
  { country: "圭亚那", countryEn: "Guyana", capital: "乔治敦", capitalEn: "Georgetown", region: "南美洲" },
  { country: "苏里南", countryEn: "Suriname", capital: "帕拉马里博", capitalEn: "Paramaribo", region: "南美洲" },
  { country: "厄瓜多尔", countryEn: "Ecuador", capital: "基多", capitalEn: "Quito", region: "南美洲" },
  { country: "秘鲁", countryEn: "Peru", capital: "利马", capitalEn: "Lima", region: "南美洲" },
  { country: "巴西", countryEn: "Brazil", capital: "巴西利亚", capitalEn: "Brasilia", region: "南美洲" },
  { country: "玻利维亚", countryEn: "Bolivia", capital: "苏克雷", capitalEn: "Sucre", region: "南美洲" },
  { country: "智利", countryEn: "Chile", capital: "圣地亚哥", capitalEn: "Santiago", region: "南美洲" },
  { country: "阿根廷", countryEn: "Argentina", capital: "布宜诺斯艾利斯", capitalEn: "Buenos Aires", region: "南美洲" },
  { country: "巴拉圭", countryEn: "Paraguay", capital: "亚松森", capitalEn: "Asuncion", region: "南美洲" },
  { country: "乌拉圭", countryEn: "Uruguay", capital: "蒙得维的亚", capitalEn: "Montevideo", region: "南美洲" },

  // 大洋洲
  { country: "澳大利亚", countryEn: "Australia", capital: "堪培拉", capitalEn: "Canberra", region: "大洋洲" },
  { country: "新西兰", countryEn: "New Zealand", capital: "惠灵顿", capitalEn: "Wellington", region: "大洋洲" },
  { country: "巴布亚新几内亚", countryEn: "Papua New Guinea", capital: "莫尔兹比港", capitalEn: "Port Moresby", region: "大洋洲" },
  { country: "斐济", countryEn: "Fiji", capital: "苏瓦", capitalEn: "Suva", region: "大洋洲" },
  { country: "所罗门群岛", countryEn: "Solomon Islands", capital: "霍尼亚拉", capitalEn: "Honiara", region: "大洋洲" },
  { country: "瓦努阿图", countryEn: "Vanuatu", capital: "维拉港", capitalEn: "Port Vila", region: "大洋洲" },
  { country: "萨摩亚", countryEn: "Samoa", capital: "阿皮亚", capitalEn: "Apia", region: "大洋洲" },
  { country: "汤加", countryEn: "Tonga", capital: "努库阿洛法", capitalEn: "Nuku'alofa", region: "大洋洲" },
  { country: "密克罗尼西亚", countryEn: "Micronesia", capital: "帕利基尔", capitalEn: "Palikir", region: "大洋洲" },
  { country: "马绍尔群岛", countryEn: "Marshall Islands", capital: "马久罗", capitalEn: "Majuro", region: "大洋洲" },
  { country: "帕劳", countryEn: "Palau", capital: "恩吉鲁穆德", capitalEn: "Ngerulmud", region: "大洋洲" },
  { country: "瑙鲁", countryEn: "Nauru", capital: "亚伦", capitalEn: "Yaren", region: "大洋洲" },
  { country: "基里巴斯", countryEn: "Kiribati", capital: "塔拉瓦", capitalEn: "Tarawa", region: "大洋洲" },
  { country: "图瓦卢", countryEn: "Tuvalu", capital: "富纳富提", capitalEn: "Funafuti", region: "大洋洲" },
  { country: "库克群岛", countryEn: "Cook Islands", capital: "阿瓦鲁阿", capitalEn: "Avarua", region: "大洋洲" },
];
