// 垃圾分类查询数据 — 上海/北京标准分类。
// 四类：可回收物、有害垃圾、厨余垃圾（湿垃圾）、其他垃圾（干垃圾）。
// 数据来源：上海/北京生活垃圾分类标准常见物品。

export type GarbageCategory =
  | "可回收物"
  | "有害垃圾"
  | "厨余垃圾"
  | "其他垃圾";

export interface GarbageItem {
  name: string;
  category: GarbageCategory;
  tip: string;
}

export const CATEGORY_COLOR: Record<GarbageCategory, string> = {
  可回收物: "#136CE9",
  有害垃圾: "#E53935",
  厨余垃圾: "#43A047",
  其他垃圾: "#8E8E8E",
};

export const CATEGORY_DESC: Record<GarbageCategory, string> = {
  可回收物: "适宜回收、可循环利用的生活废弃物。投放时保持清洁干燥，避免污染。",
  有害垃圾: "对人体健康或自然环境造成直接或潜在危害的废弃物。需轻投轻放，易破损物请包裹后投放。",
  厨余垃圾: "易腐烂的生物质废弃物。应去除包装后投放，做到破袋投放。",
  其他垃圾: "除可回收物、有害垃圾、厨余垃圾以外的其他生活废弃物。",
};

export const GARBAGE_DATA: GarbageItem[] = [
  // 可回收物
  { name: "报纸", category: "可回收物", tip: "保持干燥，铺平后投放。" },
  { name: "纸箱", category: "可回收物", tip: "拆开压平后投放，避免受潮。" },
  { name: "纸袋", category: "可回收物", tip: "保持干净干燥。" },
  { name: "打印纸", category: "可回收物", tip: "整洁的废纸可回收。" },
  { name: "书本", category: "可回收物", tip: "捐献或回收。" },
  { name: "杂志", category: "可回收物", tip: "保持干燥。" },
  { name: "信封", category: "可回收物", tip: "干净的信封可回收。" },
  { name: "广告纸", category: "可回收物", tip: "保持干燥。" },
  { name: "纸杯", category: "其他垃圾", tip: "内层有防水膜，不可回收，属其他垃圾。" },
  { name: "塑料瓶", category: "可回收物", tip: "倒空液体，压扁后投放。" },
  { name: "塑料袋", category: "其他垃圾", tip: "普通塑料袋难回收，属其他垃圾。" },
  { name: "塑料玩具", category: "可回收物", tip: "清理后投放。" },
  { name: "塑料盆", category: "可回收物", tip: "干净的塑料盆可回收。" },
  { name: "塑料勺", category: "其他垃圾", tip: "一次性塑料餐具属其他垃圾。" },
  { name: "矿泉水瓶", category: "可回收物", tip: "倒空压扁后投放。" },
  { name: "饮料瓶", category: "可回收物", tip: "倒空液体，压扁投放。" },
  { name: "洗发水瓶", category: "可回收物", tip: "倒空内容物后投放。" },
  { name: "洗衣液瓶", category: "可回收物", tip: "清洗干净后投放。" },
  { name: "玻璃瓶", category: "可回收物", tip: "清洗后投放，注意防止破碎。" },
  { name: "玻璃杯", category: "可回收物", tip: "完好可回收，破碎请包裹后投其他垃圾。" },
  { name: "玻璃镜子", category: "其他垃圾", tip: "镜子属其他垃圾。" },
  { name: "易拉罐", category: "可回收物", tip: "压扁后投放。" },
  { name: "铝罐", category: "可回收物", tip: "压扁后投放。" },
  { name: "铁罐", category: "可回收物", tip: "清洗干净后投放。" },
  { name: "金属餐具", category: "可回收物", tip: "干净的金属餐具可回收。" },
  { name: "旧锅", category: "可回收物", tip: "铁锅、铝锅可回收。" },
  { name: "旧衣服", category: "可回收物", tip: "清洗叠好后投放回收箱。" },
  { name: "旧鞋子", category: "可回收物", tip: "成对捆扎后回收。" },
  { name: "旧包", category: "可回收物", tip: "皮包、布包可回收。" },
  { name: "旧帽子", category: "可回收物", tip: "清洗干净后回收。" },
  { name: "旧床单", category: "可回收物", tip: "清洗叠好后回收。" },
  { name: "旧毛巾", category: "其他垃圾", tip: "受污染的毛巾属其他垃圾。" },
  { name: "旧手机", category: "可回收物", tip: "电子产品可回收，建议交给专业回收点。" },
  { name: "旧电脑", category: "可回收物", tip: "电子产品应送专业回收点。" },
  { name: "旧电视", category: "可回收物", tip: "大件电器联系专业回收。" },
  { name: "旧冰箱", category: "可回收物", tip: "大件电器联系专业回收。" },
  { name: "旧洗衣机", category: "可回收物", tip: "大件电器联系专业回收。" },
  { name: "旧空调", category: "可回收物", tip: "大件电器联系专业回收。" },
  { name: "充电宝", category: "有害垃圾", tip: "含锂电池，属有害垃圾。" },
  { name: "锂电池", category: "有害垃圾", tip: "含重金属，属有害垃圾。" },
  { name: "纸板", category: "可回收物", tip: "拆开压平后投放。" },
  { name: "利乐包", category: "可回收物", tip: "牛奶盒等利乐包装可回收，需清洗压扁。" },
  { name: "光盘", category: "其他垃圾", tip: "光盘属其他垃圾。" },
  { name: "U盘", category: "可回收物", tip: "电子产品可回收。" },
  { name: "耳机", category: "可回收物", tip: "电子产品可回收。" },
  { name: "键盘", category: "可回收物", tip: "电子产品可回收。" },

  // 有害垃圾
  { name: "废电池", category: "有害垃圾", tip: "含重金属，需投放有害垃圾桶。" },
  { name: "纽扣电池", category: "有害垃圾", tip: "含汞等重金属。" },
  { name: "蓄电池", category: "有害垃圾", tip: "含铅酸，属有害垃圾。" },
  { name: "过期药品", category: "有害垃圾", tip: "连同包装一起投放有害垃圾桶。" },
  { name: "药片", category: "有害垃圾", tip: "过期药品属有害垃圾。" },
  { name: "药水", category: "有害垃圾", tip: "过期药水属有害垃圾。" },
  { name: "药膏", category: "有害垃圾", tip: "过期药膏属有害垃圾。" },
  { name: "感冒药", category: "有害垃圾", tip: "过期后属有害垃圾。" },
  { name: "体温计", category: "有害垃圾", tip: "含汞，破损需妥善包裹后投放。" },
  { name: "水银温度计", category: "有害垃圾", tip: "含汞，属有害垃圾。" },
  { name: "血压计", category: "有害垃圾", tip: "含汞，属有害垃圾。" },
  { name: "荧光灯管", category: "有害垃圾", tip: "含汞，需轻放。" },
  { name: "节能灯", category: "有害垃圾", tip: "含汞，属有害垃圾。" },
  { name: "灯泡", category: "有害垃圾", tip: "白炽灯泡部分属有害垃圾。" },
  { name: "杀虫剂", category: "有害垃圾", tip: "含化学物质，属有害垃圾。" },
  { name: "消毒剂", category: "有害垃圾", tip: "含化学物质，属有害垃圾。" },
  { name: "油漆", category: "有害垃圾", tip: "含有机溶剂，属有害垃圾。" },
  { name: "油漆桶", category: "有害垃圾", tip: "残留油漆的桶属有害垃圾。" },
  { name: "涂料", category: "有害垃圾", tip: "含化学物质，属有害垃圾。" },
  { name: "指甲油", category: "有害垃圾", tip: "含有机溶剂，属有害垃圾。" },
  { name: "染发剂", category: "有害垃圾", tip: "含化学物质，属有害垃圾。" },
  { name: "墨盒", category: "有害垃圾", tip: "打印机墨盒属有害垃圾。" },
  { name: "硒鼓", category: "有害垃圾", tip: "打印机硒鼓属有害垃圾。" },
  { name: "相纸", category: "有害垃圾", tip: "含化学物质，属有害垃圾。" },
  { name: "胶卷", category: "有害垃圾", tip: "含银等重金属，属有害垃圾。" },
  { name: "农药", category: "有害垃圾", tip: "含毒性物质，属有害垃圾。" },
  { name: "化肥", category: "有害垃圾", tip: "残留化学品属有害垃圾。" },

  // 厨余垃圾（湿垃圾）
  { name: "剩菜剩饭", category: "厨余垃圾", tip: "沥干后破袋投放。" },
  { name: "米饭", category: "厨余垃圾", tip: "剩饭属厨余垃圾。" },
  { name: "面条", category: "厨余垃圾", tip: "剩面条属厨余垃圾。" },
  { name: "馒头", category: "厨余垃圾", tip: "剩馒头属厨余垃圾。" },
  { name: "面包", category: "厨余垃圾", tip: "过期面包属厨余垃圾。" },
  { name: "饼干", category: "厨余垃圾", tip: "过期饼干属厨余垃圾。" },
  { name: "蛋糕", category: "厨余垃圾", tip: "剩蛋糕属厨余垃圾。" },
  { name: "水果皮", category: "厨余垃圾", tip: "果皮属厨余垃圾。" },
  { name: "苹果皮", category: "厨余垃圾", tip: "果皮属厨余垃圾。" },
  { name: "香蕉皮", category: "厨余垃圾", tip: "果皮属厨余垃圾。" },
  { name: "西瓜皮", category: "厨余垃圾", tip: "果皮属厨余垃圾。" },
  { name: "橘子皮", category: "厨余垃圾", tip: "果皮属厨余垃圾。" },
  { name: "橙子皮", category: "厨余垃圾", tip: "果皮属厨余垃圾。" },
  { name: "柚子皮", category: "厨余垃圾", tip: "果皮属厨余垃圾。" },
  { name: "菠萝皮", category: "厨余垃圾", tip: "果皮属厨余垃圾。" },
  { name: "果核", category: "厨余垃圾", tip: "小果核属厨余垃圾。" },
  { name: "苹果核", category: "厨余垃圾", tip: "果核属厨余垃圾。" },
  { name: "桃核", category: "厨余垃圾", tip: "小果核属厨余垃圾。" },
  { name: "椰子壳", category: "其他垃圾", tip: "难腐烂，属其他垃圾。" },
  { name: "大棒骨", category: "其他垃圾", tip: "难腐烂，属其他垃圾。" },
  { name: "骨头", category: "其他垃圾", tip: "大块骨头难腐烂，属其他垃圾。" },
  { name: "鸡骨头", category: "厨余垃圾", tip: "小骨头属厨余垃圾。" },
  { name: "鱼骨头", category: "厨余垃圾", tip: "鱼刺属厨余垃圾。" },
  { name: "蛋壳", category: "厨余垃圾", tip: "蛋壳属厨余垃圾。" },
  { name: "茶叶渣", category: "厨余垃圾", tip: "沥干后投放。" },
  { name: "咖啡渣", category: "厨余垃圾", tip: "沥干后投放。" },
  { name: "菜叶", category: "厨余垃圾", tip: "菜叶属厨余垃圾。" },
  { name: "菜根", category: "厨余垃圾", tip: "菜根属厨余垃圾。" },
  { name: "烂菜叶", category: "厨余垃圾", tip: "腐烂蔬菜属厨余垃圾。" },
  { name: "果皮", category: "厨余垃圾", tip: "果皮属厨余垃圾。" },
  { name: "剩菜", category: "厨余垃圾", tip: "沥干后破袋投放。" },
  { name: "过期食品", category: "厨余垃圾", tip: "去除包装后投放。" },
  { name: "过期牛奶", category: "厨余垃圾", tip: "倒掉液体，包装另投。" },
  { name: "过期酸奶", category: "厨余垃圾", tip: "倒掉内容物，包装另投。" },
  { name: "调味料", category: "厨余垃圾", tip: "过期调味料属厨余垃圾。" },
  { name: "中药渣", category: "厨余垃圾", tip: "中药药渣属厨余垃圾。" },
  { name: "宠物饲料", category: "厨余垃圾", tip: "过期饲料属厨余垃圾。" },

  // 其他垃圾（干垃圾）
  { name: "烟头", category: "其他垃圾", tip: "熄灭后投放。" },
  { name: "烟灰", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "纸巾", category: "其他垃圾", tip: "受污染的纸巾不可回收。" },
  { name: "湿纸巾", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "餐巾纸", category: "其他垃圾", tip: "用过的餐巾纸不可回收。" },
  { name: "卫生纸", category: "其他垃圾", tip: "卫生纸不可回收。" },
  { name: "卫生巾", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "纸尿裤", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "尿不湿", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "猫砂", category: "其他垃圾", tip: "宠物粪便垃圾属其他垃圾。" },
  { name: "狗粮", category: "厨余垃圾", tip: "过期狗粮属厨余垃圾。" },
  { name: "陶瓷碎片", category: "其他垃圾", tip: "包裹后投放。" },
  { name: "碎玻璃", category: "其他垃圾", tip: "包裹后投放，避免伤人。" },
  { name: "镜子碎片", category: "其他垃圾", tip: "包裹后投放。" },
  { name: "一次性筷子", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "一次性餐盒", category: "其他垃圾", tip: "受污染的外卖盒属其他垃圾。" },
  { name: "外卖盒", category: "其他垃圾", tip: "受污染的外卖盒属其他垃圾。" },
  { name: "塑料袋", category: "其他垃圾", tip: "普通塑料袋难回收。" },
  { name: "保鲜膜", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "胶带", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "胶水", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "橡皮泥", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "创可贴", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "口罩", category: "其他垃圾", tip: "一次性口罩属其他垃圾。" },
  { name: "棉签", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "牙签", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "毛发", category: "其他垃圾", tip: "头发等属其他垃圾。" },
  { name: "灰尘", category: "其他垃圾", tip: "清扫的灰尘属其他垃圾。" },
  { name: "扫帚", category: "其他垃圾", tip: "损坏的扫帚属其他垃圾。" },
  { name: "拖把", category: "其他垃圾", tip: "损坏的拖把属其他垃圾。" },
  { name: "海绵", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "抹布", category: "其他垃圾", tip: "受污染的抹布属其他垃圾。" },
  { name: "鞋刷", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "铅笔屑", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "橡皮擦", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "修正带", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "打火机", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "伞", category: "其他垃圾", tip: "损坏的雨伞属其他垃圾。" },
  { name: "眼镜", category: "其他垃圾", tip: "旧眼镜属其他垃圾。" },
  { name: "照片", category: "其他垃圾", tip: "相纸属其他垃圾。" },
  { name: "鲜花", category: "厨余垃圾", tip: "枯萎的鲜花属厨余垃圾。" },
  { name: "盆栽", category: "厨余垃圾", tip: "植物属厨余垃圾，花盆另投。" },

  // 常见易混淆物品补充
  { name: "牛奶盒", category: "可回收物", tip: "利乐包装，清洗压扁后回收。" },
  { name: "快递盒", category: "可回收物", tip: "拆开压平后回收。" },
  { name: "快递袋", category: "其他垃圾", tip: "塑料快递袋属其他垃圾。" },
  { name: "气泡膜", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "泡沫箱", category: "可回收物", tip: "干净的泡沫箱可回收。" },
  { name: "保鲜盒", category: "可回收物", tip: "干净的塑料保鲜盒可回收。" },
  { name: "牙刷", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "牙膏皮", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "梳子", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "奶嘴", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "奶瓶", category: "可回收物", tip: "干净的塑料奶瓶可回收。" },
  { name: "调料瓶", category: "可回收物", tip: "玻璃调料瓶可回收。" },
  { name: "酒瓶", category: "可回收物", tip: "玻璃酒瓶可回收。" },
  { name: "化妆品瓶", category: "可回收物", tip: "清洗干净后回收。" },
  { name: "口红", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "粉底液瓶", category: "可回收物", tip: "清洗后可回收。" },
  { name: "面膜包装", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "剃须刀", category: "可回收物", tip: "电动剃须刀属可回收物。" },
  { name: "刀片", category: "有害垃圾", tip: "锋利刀片包裹后投有害垃圾。" },
  { name: "图钉", category: "其他垃圾", tip: "属其他垃圾。" },
  { name: "订书钉", category: "其他垃圾", tip: "属其他垃圾。" },
];
