// 高校查询 — 中国知名大学数据（name + province + city + type + tags + website）。

export interface School {
  name: string;
  province: string;
  city: string;
  type: string;
  tags: string[];
  website: string;
  is985: boolean;
  is211: boolean;
}

export const SCHOOLS: School[] = [
  { name: "北京大学", province: "北京", city: "北京", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.pku.edu.cn" },
  { name: "清华大学", province: "北京", city: "北京", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.tsinghua.edu.cn" },
  { name: "中国人民大学", province: "北京", city: "北京", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.ruc.edu.cn" },
  { name: "北京师范大学", province: "北京", city: "北京", type: "师范", tags: ["985", "211", "双一流"], website: "https://www.bnu.edu.cn" },
  { name: "北京航空航天大学", province: "北京", city: "北京", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.buaa.edu.cn" },
  { name: "北京理工大学", province: "北京", city: "北京", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.bit.edu.cn" },
  { name: "中国农业大学", province: "北京", city: "北京", type: "农林", tags: ["985", "211", "双一流"], website: "https://www.cau.edu.cn" },
  { name: "中央民族大学", province: "北京", city: "北京", type: "民族", tags: ["985", "211", "双一流"], website: "https://www.muc.edu.cn" },
  { name: "北京邮电大学", province: "北京", city: "北京", type: "理工", tags: ["211", "双一流"], website: "https://www.bupt.edu.cn" },
  { name: "中央财经大学", province: "北京", city: "北京", type: "财经", tags: ["211", "双一流"], website: "https://www.cufe.edu.cn" },
  { name: "对外经济贸易大学", province: "北京", city: "北京", type: "财经", tags: ["211", "双一流"], website: "https://www.uibe.edu.cn" },
  { name: "中国政法大学", province: "北京", city: "北京", type: "政法", tags: ["211", "双一流"], website: "https://www.cupl.edu.cn" },
  { name: "北京外国语大学", province: "北京", city: "北京", type: "语言", tags: ["211", "双一流"], website: "https://www.bfsu.edu.cn" },
  { name: "北京交通大学", province: "北京", city: "北京", type: "理工", tags: ["211", "双一流"], website: "https://www.bjtu.edu.cn" },
  { name: "北京科技大学", province: "北京", city: "北京", type: "理工", tags: ["211", "双一流"], website: "https://www.ustb.edu.cn" },
  { name: "中国传媒大学", province: "北京", city: "北京", type: "语言", tags: ["211", "双一流"], website: "https://www.cuc.edu.cn" },
  { name: "中央美术学院", province: "北京", city: "北京", type: "艺术", tags: ["双一流"], website: "https://www.cafa.com.cn" },
  { name: "复旦大学", province: "上海", city: "上海", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.fudan.edu.cn" },
  { name: "上海交通大学", province: "上海", city: "上海", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.sjtu.edu.cn" },
  { name: "同济大学", province: "上海", city: "上海", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.tongji.edu.cn" },
  { name: "华东师范大学", province: "上海", city: "上海", type: "师范", tags: ["985", "211", "双一流"], website: "https://www.ecnu.edu.cn" },
  { name: "华东理工大学", province: "上海", city: "上海", type: "理工", tags: ["211", "双一流"], website: "https://www.ecust.edu.cn" },
  { name: "上海财经大学", province: "上海", city: "上海", type: "财经", tags: ["211", "双一流"], website: "https://www.sufe.edu.cn" },
  { name: "上海外国语大学", province: "上海", city: "上海", type: "语言", tags: ["211", "双一流"], website: "https://www.shisu.edu.cn" },
  { name: "上海大学", province: "上海", city: "上海", type: "综合", tags: ["211", "双一流"], website: "https://www.shu.edu.cn" },
  { name: "东华大学", province: "上海", city: "上海", type: "理工", tags: ["211", "双一流"], website: "https://www.dhu.edu.cn" },
  { name: "浙江大学", province: "浙江", city: "杭州", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.zju.edu.cn" },
  { name: "南京大学", province: "江苏", city: "南京", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.nju.edu.cn" },
  { name: "东南大学", province: "江苏", city: "南京", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.seu.edu.cn" },
  { name: "南京理工大学", province: "江苏", city: "南京", type: "理工", tags: ["211", "双一流"], website: "https://www.njust.edu.cn" },
  { name: "南京航空航天大学", province: "江苏", city: "南京", type: "理工", tags: ["211", "双一流"], website: "https://www.nuaa.edu.cn" },
  { name: "苏州大学", province: "江苏", city: "苏州", type: "综合", tags: ["211", "双一流"], website: "https://www.suda.edu.cn" },
  { name: "河海大学", province: "江苏", city: "南京", type: "理工", tags: ["211", "双一流"], website: "https://www.hhu.edu.cn" },
  { name: "中国药科大学", province: "江苏", city: "南京", type: "医药", tags: ["211", "双一流"], website: "https://www.cpu.edu.cn" },
  { name: "南京师范大学", province: "江苏", city: "南京", type: "师范", tags: ["211", "双一流"], website: "https://www.njnu.edu.cn" },
  { name: "武汉大学", province: "湖北", city: "武汉", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.whu.edu.cn" },
  { name: "华中科技大学", province: "湖北", city: "武汉", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.hust.edu.cn" },
  { name: "武汉理工大学", province: "湖北", city: "武汉", type: "理工", tags: ["211", "双一流"], website: "https://www.whut.edu.cn" },
  { name: "中南财经政法大学", province: "湖北", city: "武汉", type: "财经", tags: ["211", "双一流"], website: "https://www.zuel.edu.cn" },
  { name: "华中师范大学", province: "湖北", city: "武汉", type: "师范", tags: ["211", "双一流"], website: "https://www.ccnu.edu.cn" },
  { name: "湖南大学", province: "湖南", city: "长沙", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.hnu.edu.cn" },
  { name: "中南大学", province: "湖南", city: "长沙", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.csu.edu.cn" },
  { name: "湖南师范大学", province: "湖南", city: "长沙", type: "师范", tags: ["211", "双一流"], website: "https://www.hunnu.edu.cn" },
  { name: "国防科技大学", province: "湖南", city: "长沙", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.nudt.edu.cn" },
  { name: "中山大学", province: "广东", city: "广州", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.sysu.edu.cn" },
  { name: "华南理工大学", province: "广东", city: "广州", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.scut.edu.cn" },
  { name: "暨南大学", province: "广东", city: "广州", type: "综合", tags: ["211", "双一流"], website: "https://www.jnu.edu.cn" },
  { name: "华南师范大学", province: "广东", city: "广州", type: "师范", tags: ["211", "双一流"], website: "https://www.scnu.edu.cn" },
  { name: "深圳大学", province: "广东", city: "深圳", type: "综合", tags: [], website: "https://www.szu.edu.cn" },
  { name: "南方科技大学", province: "广东", city: "深圳", type: "理工", tags: ["双一流"], website: "https://www.sustech.edu.cn" },
  { name: "四川大学", province: "四川", city: "成都", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.scu.edu.cn" },
  { name: "电子科技大学", province: "四川", city: "成都", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.uestc.edu.cn" },
  { name: "西南财经大学", province: "四川", city: "成都", type: "财经", tags: ["211", "双一流"], website: "https://www.swufe.edu.cn" },
  { name: "西安交通大学", province: "陕西", city: "西安", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.xjtu.edu.cn" },
  { name: "西北工业大学", province: "陕西", city: "西安", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.nwpu.edu.cn" },
  { name: "西安电子科技大学", province: "陕西", city: "西安", type: "理工", tags: ["211", "双一流"], website: "https://www.xidian.edu.cn" },
  { name: "西北农林科技大学", province: "陕西", city: "咸阳", type: "农林", tags: ["985", "211", "双一流"], website: "https://www.nwsuaf.edu.cn" },
  { name: "长安大学", province: "陕西", city: "西安", type: "理工", tags: ["211", "双一流"], website: "https://www.chd.edu.cn" },
  { name: "南开大学", province: "天津", city: "天津", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.nankai.edu.cn" },
  { name: "天津大学", province: "天津", city: "天津", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.tju.edu.cn" },
  { name: "山东大学", province: "山东", city: "济南", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.sdu.edu.cn" },
  { name: "中国海洋大学", province: "山东", city: "青岛", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.ouc.edu.cn" },
  { name: "吉林大学", province: "吉林", city: "长春", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.jlu.edu.cn" },
  { name: "哈尔滨工业大学", province: "黑龙江", city: "哈尔滨", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.hit.edu.cn" },
  { name: "大连理工大学", province: "辽宁", city: "大连", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.dlut.edu.cn" },
  { name: "东北大学", province: "辽宁", city: "沈阳", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.neu.edu.cn" },
  { name: "厦门大学", province: "福建", city: "厦门", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.xmu.edu.cn" },
  { name: "福州大学", province: "福建", city: "福州", type: "理工", tags: ["211", "双一流"], website: "https://www.fzu.edu.cn" },
  { name: "重庆大学", province: "重庆", city: "重庆", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.cqu.edu.cn" },
  { name: "兰州大学", province: "甘肃", city: "兰州", type: "综合", tags: ["985", "211", "双一流"], website: "https://www.lzu.edu.cn" },
  { name: "中国科学技术大学", province: "安徽", city: "合肥", type: "理工", tags: ["985", "211", "双一流"], website: "https://www.ustc.edu.cn" },
  { name: "合肥工业大学", province: "安徽", city: "合肥", type: "理工", tags: ["211", "双一流"], website: "https://www.hfut.edu.cn" },
  { name: "郑州大学", province: "河南", city: "郑州", type: "综合", tags: ["211", "双一流"], website: "https://www.zzu.edu.cn" },
  { name: "南昌大学", province: "江西", city: "南昌", type: "综合", tags: ["211", "双一流"], website: "https://www.ncu.edu.cn" },
  { name: "云南大学", province: "云南", city: "昆明", type: "综合", tags: ["211", "双一流"], website: "https://www.ynu.edu.cn" },
  { name: "贵州大学", province: "贵州", city: "贵阳", type: "综合", tags: ["211", "双一流"], website: "https://www.gzu.edu.cn" },
  { name: "广西大学", province: "广西", city: "南宁", type: "综合", tags: ["211", "双一流"], website: "https://www.gxu.edu.cn" },
  { name: "海南大学", province: "海南", city: "海口", type: "综合", tags: ["211", "双一流"], website: "https://www.hainanu.edu.cn" },
  { name: "内蒙古大学", province: "内蒙古", city: "呼和浩特", type: "综合", tags: ["211", "双一流"], website: "https://www.imu.edu.cn" },
  { name: "新疆大学", province: "新疆", city: "乌鲁木齐", type: "综合", tags: ["211", "双一流"], website: "https://www.xju.edu.cn" },
  { name: "西藏大学", province: "西藏", city: "拉萨", type: "综合", tags: ["211", "双一流"], website: "https://www.utibet.edu.cn" },
  { name: "宁夏大学", province: "宁夏", city: "银川", type: "综合", tags: ["211", "双一流"], website: "https://www.nxu.edu.cn" },
  { name: "青海大学", province: "青海", city: "西宁", type: "综合", tags: ["211", "双一流"], website: "https://www.qhu.edu.cn" },
  { name: "延边大学", province: "吉林", city: "延吉", type: "综合", tags: ["211", "双一流"], website: "https://www.ybu.edu.cn" },
  { name: "石河子大学", province: "新疆", city: "石河子", type: "综合", tags: ["211", "双一流"], website: "https://www.shzu.edu.cn" },
  { name: "北京体育大学", province: "北京", city: "北京", type: "体育", tags: ["211", "双一流"], website: "https://www.bsu.edu.cn" },
  { name: "中央音乐学院", province: "北京", city: "北京", type: "艺术", tags: ["211", "双一流"], website: "https://www.ccom.edu.cn" },
].map((s) => ({ ...s, is985: s.tags.includes("985"), is211: s.tags.includes("211") }));
